version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    groups:
      frontend:
        patterns:
          - "@vitejs/*"
          - "@vue/*"
          - "vite"
          - "vitest"
          - "vue*"
          - "tailwindcss"
          - "@tailwindcss/*"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
